### DISCUSSION TITLE
Is there any template to configure the datasource using grafana provisioning system (yaml file)?

### DISCUSSION THREAD

**Discussion by elehcim** [HadesArchitect/GrafanaCassandraDatasource#185] [Q&A] [answered]
Hello, is there any example on how to configure this datasource with yaml file?
I cannot find any.
On the documentation I found only the UI way to configure it.

I'd like something like:

```yaml
apiVersion: 1
datasources:
  - name: cassandra
    type: "Apache Cassandra"
    url: cassandra:9032
    access: proxy
...
```

similar to https://grafana.com/docs/grafana/latest/administration/provisioning/?utm_source=grafana_ds_list#example-data-source-configuration-file

Could you please help me?
Thanks!

**Comment by elehcim** [comment, marked as answer]
I found out that this is a possible one (note the `type` field):

```yaml
apiVersion: 1

datasources:
  - name: Cassandra
    type: hadesarchitect-cassandra-datasource
    access: proxy
    url: http://cassandra:9042
    isDefault: false
    jsonData:
      authType: "none"            # Options: none, basic
      consistency: "ONE"           # Optional: Consistency level (e.g., ONE, QUORUM)
      defaultKeyspace: "mykeyspace"
```
