### ISSUE TITLE
Modified Signature Error

### ISSUE THREAD

**Issue by Snikz18** [HadesArchitect/GrafanaCassandraDatasource#135]
I've been trying to run version 2.1 of the plugin on grafana 8.4.1 however I keep getting modified signature error.
![image](https://user-images.githubusercontent.com/102979016/166258536-4f120113-4804-426a-b4c2-4877cdc47d95.png)

I'm running everything using docker-compose and then copying the unzipped plugin to the grafana/plugins folder, here's  my docker compose file:
```
version: '3'
services:
  grafana8:
    image: grafana/grafana:8.4.1
    ports:
      - "3001:3001"
    environment:
      GF_LOG_LEVEL: error
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: hadesarchitect-cassandra-datasource
      GF_SERVER_HTTP_PORT: 3001
    volumes:
      - /var/lib/grafana
      - ./dist:/var/lib/grafana/plugins/cassandra
```
Note that I'm also changing the grafana.ini and adding allow_loading_unsigned_plugins=hadesarchitect-cassandra-datasource afterwards.
I'm also using version 1 of the plugin with grafana 7 and that is working however we've run into some limitations which require grafana 8.
