### ISSUE TITLE
Add support for provisioning

### ISSUE THREAD

**Issue by HadesArchitect** [HadesArchitect/GrafanaCassandraDatasource#210]
https://grafana.com/docs/grafana/latest/administration/provisioning/#data-sources

- [x] Test/fix jsonSecure (via https://github.com/HadesArchitect/GrafanaCassandraDatasource/issues/210#issuecomment-2946684330)
- [ ] Provide the certificates as strings (via https://github.com/HadesArchitect/GrafanaCassandraDatasource/issues/210#issuecomment-2961903953)
- [ ] Update documentation accordingly

**Comment by tnielens-centrica** [comment]
I tested successfully my Astra data source through provisioning with the following configuration.
```yaml
     - name: "Cassandra / Astra DB"
       type: hadesarchitect-cassandra-datasource
       access: proxy
       url: "mydb.astra.datastax.com:29042"
       jsonData:
         keyspace: keyspace
         consistency: ONE
         user: myUser
         certPath: /tmp/cert
         rootPath: /tmp/key
         caPath: /tmp/ca.crt
         useCustomTLS: true
         allowInsecureTLS: false
       secureJsonData:
         password: myPassword
```

**Comment by QuinnBast** [comment]
Interesting. What version of Grafana/Helm chart/This plugin are you using?

**Comment by tnielens-centrica** [comment]
Local docker setup, no helm chart involved.
Grafana v12.0.1 (80658a73c5)
hadesarchitect-cassandra-datasource v3.0.0

**Comment by tnielens-centrica** [comment]
@HadesArchitect It would be great to be able to provide the certificates as strings instead of mounted files. That'd make the grafana kube deploys simpler.

**Comment by eeijlar** [comment]
Does this plugin support the `$__env` syntax?
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-cassandra
  namespace: mission-control
  labels:
    grafana_datasource: "1"
data:
  cassandra-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Cassandra
        type: hadesarchitect-cassandra-datasource
        access: proxy
        url: server.cluster.local.svc
        jsonData:
          consistency: "ONE"
          timeout: 10
          user: $__env{CASSANDRA_USERNAME}
          tlsSkipVerify: true
          tlsAuth: true
          tlsAuthWithCACert: true
        secureJsonData:
          basicAuthPassword: $__env{CASSANDRA_PASSWORD}
        isDefault: false
        editable: true
        readOnly: false
```

It looks like other plugins do support it but not sure about this one.
